# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stream.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'stream.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cstream.proto\x12\x06stream\"\x17\n\x07Message\x12\x0c\n\x04\x62ody\x18\x01 \x01(\x0c\"\x18\n\x08Response\x12\x0c\n\x04\x62ody\x18\x01 \x01(\t2:\n\rStreamService\x12)\n\x04\x43hat\x12\x0f.stream.Message\x1a\x10.stream.ResponseB\nZ\x08../protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stream_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\010../proto'
  _globals['_MESSAGE']._serialized_start=24
  _globals['_MESSAGE']._serialized_end=47
  _globals['_RESPONSE']._serialized_start=49
  _globals['_RESPONSE']._serialized_end=73
  _globals['_STREAMSERVICE']._serialized_start=75
  _globals['_STREAMSERVICE']._serialized_end=133
# @@protoc_insertion_point(module_scope)
